### ISSUE TITLE
List index out of range

### ISSUE THREAD

**Issue by thegoodcharlotte** [jasontbradshaw/gandi-dyndns#14]
Hi, i get index out of range error on my QNAP. I try to debug but i'm not developper. It's seem that i don't have data in domain.info method. I got active zone with my domain. 
ps: I hide my ip and domain information

Doy you have an idea of this problem?

```
[/share/CACHEDEV1_DATA/Scripts/Gandi_DynDNS] # LOG_LEVEL=DEBUG ./gandi_dyndns.py
2017-06-17 19:44:45,500 [DEBUG] Loading config file...
2017-06-17 19:44:45,500 [DEBUG] Config file loaded.
2017-06-17 19:44:45,501 [DEBUG] Getting external IP...
2017-06-17 19:44:45,797 [DEBUG] Got IP from provider http://ipinfo.io/ip: 86.237.145....
2017-06-17 19:44:47,151 [DEBUG] Got IP from provider http://ip-api.com/csv: 86.237.145...
2017-06-17 19:44:47,474 [DEBUG] Got IP from provider http://ventrilo.com/myip.php: 86.237.145....
2017-06-17 19:44:47,474 [DEBUG] External IP is: 86.237.145.....
2017-06-17 19:44:47,474 [DEBUG] Getting domain info for domain 'maxime......fr'...
Traceback (most recent call last):
  File "./gandi_dyndns.py", line 357, in <module>
    main(sys.argv)
  File "./gandi_dyndns.py", line 353, in main
    update_ip()
  File "./gandi_dyndns.py", line 242, in update_ip
    domain_info = gandi.domain.info(domain)
  File "./gandi_dyndns.py", line 69, in __call__
    return getattr(self.proxy, method)(*key_args)
  File "/mnt/ext/opt/Python/lib/python2.7/site-packages/xmlrpclib.py", line 986, in __call__
    return self.__send(self.__name, args)
  File "/mnt/ext/opt/Python/lib/python2.7/site-packages/xmlrpclib.py", line 1239, in __request
    verbose=self.__verbose
  File "/mnt/ext/opt/Python/lib/python2.7/site-packages/xmlrpclib.py", line 1037, in request
    return self._parse_response(h.getfile(), sock)
  File "/mnt/ext/opt/Python/lib/python2.7/site-packages/xmlrpclib.py", line 1133, in _parse_response
    p.feed(response)
  File "/mnt/ext/opt/Python/lib/python2.7/site-packages/xmlrpclib.py", line 505, in feed
    self._parser.Parse(data, 0)
  File "/mnt/ext/opt/Python/lib/python2.7/site-packages/xmlrpclib.py", line 733, in end
    return f(self, join(self._data, ""))
  File "/mnt/ext/opt/Python/lib/python2.7/site-packages/xmlrpclib.py", line 796, in end_struct
    dict[_stringify(items[i])] = items[i+1]
IndexError: list index out of range

```

**Comment by jasontbradshaw** [comment]
I'm not sure why this would happen, but my best guess is that there's some problem with the `maxime...` domain being used.

Did you follow all the instructions in [the README](https://github.com/jasontbradshaw/gandi-dyndns/blob/master/README.md), specifically around configuring the zone records? That could be the problem.

**Comment by jasontbradshaw** [comment]
Closing due to lack of followup.
